### ISSUE TITLE
nb_black is breaking the %load magic on jupyter lab

### ISSUE THREAD

**Issue by michaelaye** [dnanhkhoa/nb_black#1]
Hi!
Thanks for your useful extension. I discovered though that it breaks the %load magic on jupyterlab, that is loading source code into notebooks. It is **NOT** broken in notebooks, interestingly.

You can test it easily by doing:

```python
import pathlib
%load -n pathlib.Path
```
which loads the class code into jupyterlab fine.

But if you repeat it with loading your extension first:

```
%load_ext lab_black
import pathlib
%load -n pathlib.Path
```
nothing happens.

**Comment by dnanhkhoa** [comment]
Thank you for pointing it out, I will try to fix it as soon as possible.
