### ISSUE TITLE
`line_number` no longer valid in latest version of black

### ISSUE THREAD

**Issue by xoolive** [dnanhkhoa/nb_black#2]
The `line_number` parameter seems no longer valid in latest version of `black` which makes lab_black fail (silently). 

The following quick fix seems to work ok for now, though I am not sure it is enough for addressing the issue properly.

```python
if sys.version_info >= (3, 6, 0):
    from black import format_str, FileMode

    def _format_code(code):
        return format_str(src_contents=code, mode=FileMode())
```

Just for the record, since lab_black failed silently, I would recommend to change

```python
except (ValueError, TypeError):
    pass
```
into
```python
except (ValueError, TypeError) as e:
    logging.warn(e)
```

**Comment by dnanhkhoa** [comment]
Thank you for raising up this issue. I think that your solution is fine, I will check and update it as soon as possible. Thanks.

**Comment by MarvinT** [comment]
https://gist.github.com/MarvinT/a072aa992e977496974aaf492287b08c
and 
https://marvint.github.io/Black-Jupyter/

Have examples for fixing this problem or an alternative method using code-prettify.

**Comment by dnanhkhoa** [comment]
Hi @xoolive,
I have fixed this issue using the code you suggested, also tested on both Jupyter Lab and Jupyter Notebook and it works fine, so please update to the latest version. Thank you.

**Comment by dnanhkhoa** [comment]
Hi @MarvinT,
Thank you for sharing, I have checked your repo out and see that it's really helpful and convenient. :D

**Comment by xoolive** [comment]
Excellent! Works like a charm on my side.
