### ISSUE TITLE
Command line version?

### ISSUE THREAD

**Issue by Mistobaan** [dnanhkhoa/nb_black#23]
Would it be possible to run this from the command line on a saved notebook?

```
nb_black mynotebook.ipynb
```

**Comment by dnanhkhoa** [comment]
Hi @Mistobaan,

I don't think it's possible to do that using this extension but you can do that in another way by converting your notebook to Python file, then format it using black (it supports cmd already) then get back to notebook format. If works, you can wrap up these 3 steps into a bash file or something like that.
