### ISSUE TITLE
it does not format in WSL

### ISSUE THREAD

**Issue by uremember809** [dnanhkhoa/nb_black#3]
I have jupyter installed in windowsubsystem linux, python 3.6.8. Nb_black installed fine, but cells will not get formated.

**Comment by dnanhkhoa** [comment]
Hi, thank you for pointing it out,
Have you put this line `%load_ext nb_black` into the first cell of your notebook? Or did you get any error message?

**Comment by uremember809** [comment]
I am not able to identify what is wrong.

I %load_ext lab_black

no error message, code runs, just won't format.

However, on another machine it works fine.
