### ISSUE TITLE
Option to use yapf?

### ISSUE THREAD

**Issue by filyp** [dnanhkhoa/nb_black#31]
Thanks for this awesome extension! It's really effortless.
My only issue is, that I'd prefer to use yapf. I've seen that it already does for python<3.6, so adding this option would be easy, for example by adding file lab_yapf.py.

I can add it if you say it's ok.

**Comment by MarcoGorelli** [comment]
Hi @fsondej - if `yapf` if out-of-scope for this library, then (sorry for the self-promotion) you may be able to run it via [nbqa](https://github.com/nbQA-dev/nbQA)
