### ISSUE TITLE
Is it possible to use Black / nb_black when editing python files in JupyterLab? eom

### ISSUE THREAD

**Issue by jgunstone** [dnanhkhoa/nb_black#37]

**Comment by ichbinallen** [comment]
nb_black doesn't seem to work in jupyter-lab.  However, 
`%load_ext lab_black` worked for me.

**Comment by jgunstone** [comment]
hi there - yes - `%load_ext lab_black` works well for editing Notebooks. 
i was wondering if it was possible to enable it when editing .py files in jupyterlab such that black is run on-save. 

cheers

**Comment by jgunstone** [comment]
it works in cells so I close
