### ISSUE TITLE
latest version doesn't allow help magic in jlab

### ISSUE THREAD

**Issue by michaelaye** [dnanhkhoa/nb_black#4]
I installed version 1.0.4 from pypi.

Now I cannot get help listings:

<img width="747" alt="Screenshot 2019-04-22 02 03 19" src="https://user-images.githubusercontent.com/69774/56476589-07834100-64a3-11e9-9379-c643d52d20a3.png">

Using macOS 10.14.3

**Comment by dnanhkhoa** [comment]
Thank you for pointing it out, I will fix this error on this Saturday.

**Comment by dnanhkhoa** [comment]
I have fixed it, so please update the package to the latest version. Thanks.
