### ISSUE TITLE
Does not work with older installations of black - illegible error

### ISSUE THREAD

**Issue by kristomi** [dnanhkhoa/nb_black#7]
I had black 18.9b0 installed, and in that version the FileMode() takes an argument. So the lab_black failed. After I upgraded black to the latest version (currently 19.3b0), everything worked fine again. Should you perhaps specify some requirements for this library so that this doesn't happen to other people?

**Comment by dnanhkhoa** [comment]
Thank you for your suggestion, I will specify the black version in the setup file to avoid this problem.
